"""ALARA input-bundle adapter for ParaStell activation spectra."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import subprocess
from typing import Sequence

from .model import (
    ActivationRegion,
    ActivationSchedule,
    base_manifest,
    write_json,
)
from .spectrum_export import ActivationSpectrum


@dataclass(frozen=True)
class AlaraConfiguration:
    executable: Path | None
    library_group_count: int
    library_flux_ordering: str
    library_directives: tuple[str, ...]
    truncation: float = 1.0e-8

    def __post_init__(self):
        if self.library_group_count <= 0:
            raise ValueError("ALARA library group count must be positive")
        if self.library_flux_ordering not in {"ascending", "descending"}:
            raise ValueError("invalid ALARA library flux ordering")
        if not self.library_directives:
            raise ValueError("ALARA library directives are required")
        if self.truncation <= 0.0:
            raise ValueError("ALARA truncation must be positive")


class AlaraActivationBridge:
    """Prepare auditable point-geometry ALARA problems per transport region."""

    def __init__(self, configuration: AlaraConfiguration):
        self.configuration = configuration

    def prepare(
        self,
        output_dir: str | Path,
        region: ActivationRegion,
        schedule: ActivationSchedule,
        spectrum: ActivationSpectrum,
        *,
        mixture_lines: Sequence[str],
    ) -> Path:
        if spectrum.region_id != region.region_id:
            raise ValueError("spectrum and activation region IDs differ")
        if (
            len(spectrum.group_flux_cm2_s)
            != self.configuration.library_group_count
        ):
            raise ValueError("spectrum does not match ALARA library groups")
        if not mixture_lines or any(
            line.strip().lower() == "end" for line in mixture_lines
        ):
            raise ValueError(
                "explicit ALARA mixture constituent lines are required"
            )
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=False)
        spectrum_path = spectrum.write_alara_flux(
            output / "flux.txt",
            ordering=self.configuration.library_flux_ordering,
        )
        active_steps = [
            step for step in schedule.steps if step.source_rate_n_s > 0.0
        ]
        if not active_steps:
            raise ValueError("ALARA schedule requires an irradiation interval")
        first_active = next(
            index
            for index, step in enumerate(schedule.steps)
            if step.source_rate_n_s > 0.0
        )
        if first_active != 0:
            raise ValueError("ALARA schedule cannot begin with cooling")
        last_active = max(
            index
            for index, step in enumerate(schedule.steps)
            if step.source_rate_n_s > 0.0
        )
        deck = [
            "# Generated by ParaStell; library directives remain user-controlled.",
            "geometry point",
            "volumes",
            f"{region.volume_cm3:.17e} {region.region_id}",
            "end",
            "mat_loading",
            f"{region.region_id} {region.material_name}",
            "end",
            f"mixture {region.material_name}",
            *mixture_lines,
            "end",
            "pulsehistory continuous",
            "1 0 s",
            "end",
            f"schedule {schedule.name}",
        ]
        flux_names: dict[float, str] = {}
        flux_blocks: list[str] = []
        for index, rate in enumerate(
            dict.fromkeys(step.source_rate_n_s for step in active_steps)
        ):
            name = f"parastell_flux_{index}"
            flux_names[rate] = name
            scale = rate / spectrum.reference_source_rate_n_s
            flux_blocks.append(
                f"flux {name} {spectrum_path.name} {scale:.17e} 0 default"
            )
        pulse_index = deck.index("pulsehistory continuous")
        deck[pulse_index:pulse_index] = flux_blocks
        for index, step in enumerate(schedule.steps[: last_active + 1]):
            if step.source_rate_n_s == 0.0:
                continue
            next_active = next(
                (
                    candidate
                    for candidate in range(index + 1, last_active + 1)
                    if schedule.steps[candidate].source_rate_n_s > 0.0
                ),
                None,
            )
            delay = 0.0
            if next_active is not None:
                delay = sum(
                    item.duration_s
                    for item in schedule.steps[index + 1 : next_active]
                )
            deck.append(
                f"{step.duration_s:.17e} s "
                f"{flux_names[step.source_rate_n_s]} continuous "
                f"{delay:.17e} s"
            )
        deck.append("end")
        trailing_cooling = schedule.steps[last_active + 1 :]
        if trailing_cooling:
            elapsed = 0.0
            deck.append("cooling")
            for step in trailing_cooling:
                elapsed += step.duration_s
                deck.append(f"{elapsed:.17e} s")
            deck.append("end")
        deck.extend(
            (
                f"truncation {self.configuration.truncation:.17e}",
                *self.configuration.library_directives,
            )
        )
        deck_path = output / "alara.inp"
        deck_path.write_text("\n".join(deck) + "\n", encoding="ascii")
        write_json(
            output / "manifest.json",
            {
                **base_manifest(),
                "kind": "alara_input_bundle",
                "backend": "alara",
                "region": region.as_dict(),
                "schedule": schedule.as_dict(),
                "spectrum": spectrum.as_dict(),
                "deck": deck_path.name,
                "flux": spectrum_path.name,
                "execution_validated": False,
            },
        )
        return output

    def run(self, bundle: str | Path) -> subprocess.CompletedProcess[str]:
        executable = self.configuration.executable
        if executable is None or not executable.is_file():
            raise FileNotFoundError("ALARA executable is not configured")
        directory = Path(bundle)
        result = subprocess.run(
            [str(executable), "alara.inp"],
            cwd=directory,
            check=True,
            capture_output=True,
            text=True,
        )
        (directory / "alara.stdout").write_text(
            result.stdout, encoding="ascii"
        )
        (directory / "alara.stderr").write_text(
            result.stderr, encoding="ascii"
        )
        manifest = json.loads(
            (directory / "manifest.json").read_text(encoding="ascii")
        )
        manifest["execution_validated"] = True
        write_json(directory / "manifest.json", manifest)
        return result
