"""FISPACT-II activation and independent-benchmark adapter."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import subprocess
from typing import Mapping

from .model import (
    ActivationRegion,
    ActivationSchedule,
    base_manifest,
    write_json,
)
from .spectrum_export import ActivationSpectrum


@dataclass(frozen=True)
class FispactConfiguration:
    executable: Path | None
    files_file: Path
    target_group_count: int = 709
    projectile: int = 1
    wall_loading_MW_m2: float = 1.0

    def __post_init__(self):
        if self.target_group_count <= 0:
            raise ValueError("FISPACT-II target group count must be positive")
        if self.projectile not in {1, 5}:
            raise ValueError(
                "FISPACT-II projectile must be neutron (1) or photon (5)"
            )
        if not self.files_file.is_file():
            raise FileNotFoundError(
                f"FISPACT-II files file not found: {self.files_file}"
            )


class FispactActivationBridge:
    """Prepare FISPACT-II input from the same physical activation contract."""

    def __init__(self, configuration: FispactConfiguration):
        self.configuration = configuration

    def prepare(
        self,
        output_dir: str | Path,
        region: ActivationRegion,
        schedule: ActivationSchedule,
        spectrum: ActivationSpectrum,
        *,
        atoms: Mapping[str, float],
    ) -> Path:
        if spectrum.region_id != region.region_id:
            raise ValueError("spectrum and activation region IDs differ")
        if (
            spectrum.particle != "neutron"
            or self.configuration.projectile != 1
        ):
            raise ValueError(
                "this activation bridge currently requires neutrons"
            )
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=False)
        arb = spectrum.write_fispact_arb_flux(
            output / "arb_flux",
            wall_loading_MW_m2=self.configuration.wall_loading_MW_m2,
        )
        files_copy = output / "files"
        files_copy.write_bytes(self.configuration.files_file.read_bytes())
        active = [
            step for step in schedule.steps if step.source_rate_n_s > 0.0
        ]
        if not active:
            raise ValueError("FISPACT-II schedule requires irradiation")
        lines = [
            "* Generated by ParaStell",
            f"PROJECTILE {self.configuration.projectile}",
            f"GRPCONVERT {len(spectrum.group_flux_cm2_s)} {self.configuration.target_group_count}",
            "GETXS 1",
            "GETDECAY 1",
            "FISPACT",
            "ATOMS",
        ]
        lines.extend(f"{name} {value:.17e}" for name, value in atoms.items())
        lines.append("END")
        for step in schedule.steps:
            flux = (
                spectrum.total_flux_cm2_s
                * step.source_rate_n_s
                / spectrum.reference_source_rate_n_s
                if step.source_rate_n_s > 0.0
                else 0.0
            )
            lines.extend(
                (f"FLUX {flux:.17e}", f"TIME {step.duration_s:.17e} SECS")
            )
        lines.append("END")
        input_path = output / "fispact.inp"
        input_path.write_text("\n".join(lines) + "\n", encoding="ascii")
        write_json(
            output / "manifest.json",
            {
                **base_manifest(),
                "kind": "fispact_input_bundle",
                "backend": "fispact-ii",
                "region": region.as_dict(),
                "schedule": schedule.as_dict(),
                "spectrum": spectrum.as_dict(),
                "input": input_path.name,
                "files": files_copy.name,
                "arb_flux": arb.name,
                "execution_validated": False,
            },
        )
        return output

    def run(self, bundle: str | Path) -> subprocess.CompletedProcess[str]:
        executable = self.configuration.executable
        if executable is None or not executable.is_file():
            raise FileNotFoundError("FISPACT-II executable is not configured")
        directory = Path(bundle)
        result = subprocess.run(
            [str(executable), "fispact.inp", "fispact.out"],
            cwd=directory,
            check=True,
            capture_output=True,
            text=True,
        )
        manifest = json.loads(
            (directory / "manifest.json").read_text(encoding="ascii")
        )
        manifest["execution_validated"] = True
        write_json(directory / "manifest.json", manifest)
        return result
