name: black
on: [push, pull_request, workflow_dispatch]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: "25.12.0"
          options: "--check --verbose"
          src: "."
